### ISSUE TITLE
Library spreadsheet normalization

### ISSUE THREAD

**Issue by libbyswanger** [geekwaytothewest/ruleslawyer-backend#7]
We want to populate the library software's `game` table with up-to-date, validated library data. We will provide Mark the lowest-lift process to share validated data with us. Ideally, we'll have him share the file where it can be retrieved with a GHA/as part of CI pipelines. This would allow us to continuously surface and handle edge cases in the data the library needs to handle.

**Tasks**

- [ ] Decide how we will ingest data (bulk upload, import script)
- [ ] Determine how Mark can share up-to-date, validated data
- [ ] Automate ingestion of up-to-date file in scheduled GHA/as part of CI pipelines
